apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-demo
  name: sample-demo
  namespace: sample-demo
spec:
  ports:
  - nodePort: 30505
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-demo
  type: NodePort
